### ISSUE TITLE
One-time code link incorrect

### ISSUE THREAD

**Issue by StaffanBetner** [j6k4m8/remailable#28]
https://my.remarkable.com/connect/mobile doesn't work for me. https://my.remarkable.com/device/mobile/connect works, and it is where I am redirected when setting up a connection in the mobile app.

**Comment by j6k4m8** [comment]
Aha! Thank you for reporting. The reMarkable cloud service has been going through some changes recently and I suppose they must have updated their links. Thank you for the heads up!

**Comment by j6k4m8** [comment]
This has been fixed I believe :)
