### ISSUE TITLE
Self Hosted - Trouble with device registration

### ISSUE THREAD

**Issue by scanis** [j6k4m8/remailable#8]
Hi there, 

Thanks so much for putting this project together! 

I've followed your instructions and I think I'm just about there in terms of a self-hosted solution. However, I'm getting the following TypeError when I try to register my device:

> `[ERROR] TypeError: register_device() got an unexpected keyword argument 'save_to_file'
> 
> Traceback (most recent call last):
>   File "/var/task/handler.py", line 609, in lambda_handler return LambdaHandler.lambda_handler(event, context)
>   File "/var/task/handler.py", line 243, in lambda_handler return handler.handler(event, context)
>   File "/var/task/handler.py", line 419, in handler result = self.run_function(app_function, event, context)
>   File "/var/task/handler.py", line 282, in run_function result = app_function(event, context)
>   File "/var/task/lambda_main.py", line 193, in upload_handler transfer_s3_path_to_remarkable(path)
>   File "/var/task/lambda_main.py", line 180, in transfer_s3_path_to_remarkable fname, fbytes = extract_pdf(message)
>   File "/var/task/lambda_main.py", line 136, in extract_pdf register_user(message.get("From"), code)
>   File "/var/task/lambda_main.py", line 104, in register_user rm.register_device(code, save_to_file=False)`

I've never actually been exposed to python before and I'm having trouble understanding how I can clear this TypeError.

**Comment by j6k4m8** [comment]
Hey @scanis! Excited to hear you're getting one running for yourself :)

#### The issue
The `save_to_file` argument is a feature that only exists in [my fork of `rmapy`](https://github.com/j6k4m8/rmapy) (the tool that we use to communicate with the reMarkable servers). The reason we need it is that we run this code in an AWS lambda runtime environment, which doesn't have a home directory like a regular machine does. So we need to run without saving a config file anywhere (`save_to_file=False`, last line of your traceback.)

#### The fix
You can ignore all of the above paragraph and just make sure you have the right rmapy installed:

```shell
# uninstall the old:
pip3 uninstall rmapy

# install the new:
pip3 install git+https://github.com/j6k4m8/rmapy
```

You can also install all of the dependencies all at once with `pip3 install -r ./requirements.txt` from the root directory of this repository :)

---

Let me know how it goes :)

**Comment by scanis** [comment]
Hey @j6k4m8 - that fix worked perfectly. 

Getting the dependencies installed was definitely the toughest part for me (given I've never used pip/zappy etc before). 

Thanks again for putting this project together. It's exactly what I needed and my implementation seems to be running smoothly.

**Comment by j6k4m8** [comment]
Awesome, I'm so glad to hear that!!
