### ISSUE TITLE
Send multiple attached PDFs to Remarkable

### ISSUE THREAD

**Issue by lieuzhenghong** [j6k4m8/remailable#9]
Referencing line 114 of lambda_main.py

**Comment by j6k4m8** [comment]
I'd love to think about this in the context of #7 too, if you're interested in broadening scope a bit. Would love to be able to attach non-PDF documents as well, but haven't had the time to really think about this. Reworking the attachments/filetypes system has been on my list for a while!

**Comment by lieuzhenghong** [comment]
Absolutely---would like it not only to handle multiple PDFs, but also ePubs and so on. Now that we have (the beginnings of..) a test suite we can have the confidence to move fast and not break things. Will be working on this shortly.

**Comment by lieuzhenghong** [comment]
This functionality has been built in Dev #13
